-- Generated by jetlin-db. Review it, edit it if needed, then commit it.
--
-- Changes:
--   * add table poll_options
--   * add table polls
--   * add table votes

CREATE TABLE poll_options (
  id INTEGER PRIMARY KEY,
  poll INTEGER NOT NULL REFERENCES polls(id),
  position INTEGER NOT NULL,
  text TEXT NOT NULL
);

CREATE TABLE polls (
  id INTEGER PRIMARY KEY,
  adminToken TEXT NOT NULL,
  createdAt INTEGER NOT NULL,
  multiple INTEGER NOT NULL,
  question TEXT NOT NULL,
  slug TEXT NOT NULL
);

CREATE TABLE votes (
  id INTEGER PRIMARY KEY,
  name TEXT NOT NULL,
  option INTEGER NOT NULL REFERENCES poll_options(id)
);
