-- Generated by jetlin-db. Review it, edit it if needed, then commit it.
--
-- Changes:
--   * add polls.visited (INTEGER)

ALTER TABLE polls ADD COLUMN visited INTEGER NOT NULL DEFAULT 0;

-- Polls that existed before this migration may already have been shared, so treat them as visited.
-- That keeps their links from changing. Only polls created from now on start out unvisited.
UPDATE polls SET visited = 1;
